name: gotest
description: "execute go tests based upon parameters"

runs:
  using: "composite"
  steps:
    - name: "Get Go version from builder container"
      id: step-detect
      shell: bash
      run: |
        make "$PWD/build-aux-local/go-version.txt"
        echo "::set-output name=go_version::$(cat "$PWD/build-aux-local/go-version.txt")"
    - name: "Install Go (${{ steps.step-detect.outputs.go_version }})"
      uses: actions/setup-go@v2
      with:
        go-version: "${{ steps.step-detect.outputs.go_version }}"
